name: linter

on:
  push:
    branches:
      - develop
      - main
      - master
      - workos
  pull_request:
    branches:
      - develop
      - main
      - master
      - workos

permissions:
  contents: write

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm install

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install JS Dependencies
        run: yarn install --frozen-lockfile

      - name: Backend Lint (Pint)
        run: ./vendor/bin/pint --test

      - name: Backend Analysis (PHPStan)
        run: ./vendor/bin/phpstan analyse --memory-limit=1G

      - name: Backend Refactoring Check (Rector)
        run: ./vendor/bin/rector process --dry-run --ansi

      - name: Frontend Lint
        run: yarn lint:check

      - name: Frontend Type Check
        run: yarn types:check
